# Generated by Django 5.0.8 on 2026-06-22 04:13

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.inventory_image_path),
        ),
    ]
