# Generated by Django 6.0.5 on 2026-06-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointments',
        ),
        migrations.AlterModelTable(
            name='patientqueue',
            table='patient_queue',
        ),
    ]
