# Generated by Django 6.0.5 on 2026-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_profile_completed_doctor_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_time_end',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time_start',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
