# Generated by Django 6.0.5 on 2026-06-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctor_available_time_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='available_time_end',
            new_name='available_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_time_start',
        ),
    ]
