# Generated by Django 6.0.5 on 2026-06-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultation',
            table='consultation',
        ),
        migrations.AlterModelTable(
            name='consultationfollowup',
            table='follow_ups',
        ),
        migrations.AlterModelTable(
            name='consultationprescription',
            table='prescription',
        ),
        migrations.AlterModelTable(
            name='consultationreport',
            table='reports',
        ),
    ]
