# Generated by Django 6.0.5 on 2026-06-20 09:31

import apps.consultations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationreport',
            name='report_file',
            field=models.FileField(upload_to=apps.consultations.models.get_report_upload_path),
        ),
    ]
